Meson, fuzzing, new CI, cross compilation
vtereshkov/umka-lang pull request #209
Opened 2022-09-10 15:07 UTC by ProkopRandacek

I wanted to add fuzz testing to umka but didn't feel like dealing with Makefiles so I unified the shell scripts and Makefiles into a meson project that can be used on all platforms.

Changes:
- switched to meson
- fuzz testing
- fuzz coverage
- debug builds use address+undefined sanitizers
- mingw crosscompilation
- github actions now compile on windows and mingw

I already found a bunch of memory leaks and some crashes using the fuzz testing.

I would normally split this into multiple PRs but the changes all rely on each other.

2022-09-11 17:50 UTC, eli-schwartz requested changes

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +add_project_arguments(['-fPIC', '-DUMKA_EXT_LIBS', '-DUMKA_BUILD'], language: 'c')
You should not be setting -fPIC yourself, as Meson does this automatically for you as part of the high-level library() functions.

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +endif
You should simply use `required: false` and look for it everywhere. On all systems where it is relevant, it is either part of libc, or a separate library distributed together with libc.

See https://mesonbuild.com/howtox.html#add-math-library-lm-portably

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +endif
You may be interested in this instead: https://mesonbuild.com/Dependencies.html#dl-libdl

It is relevant for OSes other than Linux.

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +debug = get_option('buildtype') == 'debug' or get_option('buildtype') == 'debugoptimized'
```suggestion
debug = get_option('debug')
```

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +endif
Meson does have `-Db_sanitize=address,undefined` as a core option, although the work to fix legacy debt and support arbitrary sanitizers is still ongoing...

2022-09-11 17:50 UTC, eli-schwartz commented on meson.build
> +umka_lib = both_libraries(
Shouldn't this be defined first, and then link the executables to `umka_lib` (or `umka_lib.get_static_lib()` if you absolutely need static linking)?

2022-09-12 06:29 UTC, ProkopRandacek commented on meson.build
> +endif
I did notice this option but I find it odd that it has to be specified as a command option to meson itself, rather than turned on in the `meson.build` only for specific targets.

2022-09-12 06:35 UTC, ProkopRandacek commented
Thank you for the suggestions @eli-schwartz!

2022-09-12 08:16 UTC, ProkopRandacek commented
Note that the example doesn't compile because `vtereshkov/umka-lang` doesn't have the meson files yet

2022-09-12 15:12 UTC, marekmaskarinec commented
I would be glad if the current Makefile stayed.

2023-02-08 15:07 UTC, closed without merging