Resolve vtereshkov#334 (Return user defined codes from Umka programs)
vtereshkov/umka-lang pull request #345
Opened 2024-02-13 19:17 UTC by skejeton

* And exit code parameter to `exit` (`exit(code: int)`)
* `main` can now return both `int` and `void`, returning a custom exit code and `0` exit code respectively.

2024-02-13 20:56 UTC, vtereshkov requested changes
@skejeton Hic sunt dracones. You're entering a very dangerous land. Think twice before you proceed :)

1. It's a breaking change in Umka API -- let's invite @marekmaskarinec for review
2. If we accept it, we should fix:
  2.1. API docs
  2.2. Version number (to 1.4)
  2.3. 3D camera example
  2.4. tophat
3. What if `exit(code)` is called from an Umka function called by `umkaCall()` rather than `umkaRun()`? How do we separately return the error code and the function result? Should the function return anything any result in this case?
4. What if `exit(code)` is called from a fiber other than the main fiber? Should we terminate only this fiber or also the main fiber?
5. Should we suppress memory leak analysis on `exit(0)`? On `exit(1)`? In other words, do we consider this termination to be normal or abnormal?  (See `terminatedNormally`)
6. I discourage accessing `vm.mainFiber`'s registers directly from `umka_api.c`. In view of 4, it may be merely incorrect.
7. Code organization and style:
  7.1. As `exit()` now performs a nontrivial operation, I'd propose writing a `doBuiltinExit()` function called from `doCallBuiltin()`
  7.2. I'd rename `int *result` in Umka API functions into `int *errorCode` to avoid confusion with `UmkaStackSlot *result` (see also 3)
  7.3. An opening `{` is put on a new line in my C code (as opposed to Umka code)

Questions 3 and 4 are why I haven't done this myself yet.

2024-02-13 22:48 UTC, skejeton commented
I'm not sure how the scope of this conflicts with 3D camera example, since I kept `main` with `void` compatible, nor does it use `umkaRun`.

2024-02-13 23:03 UTC, vtereshkov commented
@skejeton 

4, 6. You put the error code to the current fiber's result register:
```
fiber->reg[VM_REG_RESULT] = *fiber->top;
```
and then read the main fiber's result register:
```
*result = comp->vm.mainFiber->reg[VM_REG_RESULT].intVal;
```
Why do you think this is the same fiber?

And of course, it's better to hide the register access in `compilerRun()`, as the `umka*` functions are the highest level abstractions that ideally shouldn't know anything about the VM fibers and registers.

> I'm not sure how the scope of this conflicts with 3D camera example, since I kept main with void compatible, nor does it use umkaRun.

But is does use `umkaCall()` that should perhaps also be modified to return an optional error code,

2024-02-13 23:03 UTC, skejeton commented
I fixed 7 and 1 except for tophat (I will do it if this is merged, since this isn't in the main branch right now) and 3D example (I didn't find anything).

2024-02-13 23:17 UTC, vtereshkov commented
@marekmaskarinec What do you think an `exit(code)` should do in a function called from `umkaCall()`?

2024-02-13 23:31 UTC, skejeton commented
I'm also now confused on why whether the program terminated normally or not should affect if the memory leaks are displayed or not.

2024-02-13 23:37 UTC, vtereshkov commented
> I'm also now confused on why whether the program terminated normally or not should affect if the memory leaks are displayed or not.

An abnormal termination means that the program has not correctly exited all the scopes associated with the `{...}` blocks, so we can be 99.9 % sure it will have a lot of memory leaks. To display them makes no sense.

2024-02-13 23:41 UTC, skejeton commented
Ah I see what you mean. I'm going to modify the behavior of `OP_HALT` to pull last value from the stack, since if I emit `BUILTIN_EXIT` before the program ends, the `OP_HALT` will never execute, and alternatively, if I do `BUILTIN_EXIT` after `OP_HALT`, the instruction listing will not include the `BUILTIN_EXIT` because it prints instructions up until `OP_HALT`.

2024-02-13 23:48 UTC, vtereshkov commented
@skejeton @marekmaskarinec Another question to discuss: 

Both `umkaRun()` and `umkaCall()` already return a `bool` value to show if the program has terminated with a runtime error (including an `error()` call). 

Should we treat an `exit(1)` as something fundamentally different from an `error("OMG")`? Or maybe we can just add an (optional) error code to `error()` and change the return types of  `umkaRun()` and `umkaCall()` from `bool` to `int`? In this case, we don't need to modify `exit()`.

2024-02-13 23:58 UTC, skejeton commented
I thought about this too, however the user might not want to show an error when exiting with a parameter.

2024-02-14 00:03 UTC, skejeton commented
I also think it's better to return `false` if we keep the boolean return value, on an exit call that returns a nonzero value.

2024-02-14 00:05 UTC, vtereshkov commented
> I thought about this too, however the user might not want to show an error when exiting with a parameter.

We can make the message string optional. If it's omitted, no message is displayed.

A bigger problem is again with compatibility. The new `umkaRun`/`umkaCall` behavior will perhaps imply that the "normal" exit will produce a zero result (implicitly converted to `false`). So we should carefully invert our logic everywhere.

2024-02-14 00:10 UTC, skejeton commented
I pushed the change, in this case the `exit` function now works fiber-wise, there's no check for `mainFiber` in `umkaRun`, instead I modified `compilerCall` and `compilerRun` to return the exit codes of the fiber. 

I changed the behaviour of `umkaRun` and `umkaCall` to return false on a faulty exit code, however this might not be a great idea, and it might better to change `error`, as you proposed. I want to hear your opinion on this change, and if you think changing `error` would be a good idea I'll work on it.

2024-02-14 00:18 UTC, vtereshkov commented
Let's listen to Marek. It was his request, so I'd like to know if he is OK with returning error codes from `error()` (which means `handlerRuntime` for us).

2024-02-14 00:25 UTC, skejeton commented
Yeah I think so too, I'm going to budge him on the server tomorrow if he doesn't respond by then.
In my view - I think the `error` change is the most logical, the only edge case I can think of is would `error(0)` be the same as `exit()`? Maybe in that case it's a wise idea to keep the boolean to distinguish between those two.

2024-02-14 00:51 UTC, vtereshkov commented
Hmm, I finally understand what I actually wanted to say. For me, the question is not what to choose, `error` or `exit`, but whether we can handle returning an error code just as a runtime error (with `handlerRuntime`). If we can, it will greatly simplify everything.

2024-02-14 00:52 UTC, skejeton commented
What is `handlerRuntime`? I did a search on the repository and couldn't find it.

2024-02-14 00:55 UTC, vtereshkov commented
Ah, I already renamed it to a more appropriate `runtimeHandler`.

2024-02-14 01:01 UTC, skejeton commented
The only problem I can think of your solution is that the exit code still needs to be returned from `main`, but we can't call the `runtimeHandler` to set the exit code, since that wouldn't end the program gracefully.

2024-02-14 01:15 UTC, vtereshkov commented
We needn't copy C here and return anything from `main`. We can say, if `main` returns normally, it's zero. If you need a non-zero, explicitly call `exit` or `error`.

2024-02-14 01:20 UTC, skejeton commented
I agree.

2024-02-14 01:51 UTC, skejeton commented
Can't seem to figure out how to push an empty string literal. I'll figure it out tomorrow.

2024-02-14 02:36 UTC, skejeton commented
I've implemented the `error` proposal, note that I'm still returning `bool` from `umkaRun` and `umkaCall`, because I'm not sure how to handle errors with code 0. If the error is passed code 0 then `umkaRun`/`umkaCall` will return 0, indicating no error, which is incorrect.

2024-02-14 11:09 UTC, vtereshkov commented
> If the error is passed code 0 then umkaRun/umkaCall will return 0, indicating no error, which is incorrect.

Why is it incorrect? I think `exit(0)` is a no-error termination.

(Except that if a function called with `umkaCall()` has exited on its own `return`, you can use `umkaCall()` again, but if it has exited on a `exit(0)`, you cannot, and these states are indistinguishable, as `umkaCall()` returns 0 in both cases. However, I don't think this is very important.)

2024-02-14 11:14 UTC, skejeton commented
I see. Then would the error message on `error(0)` be displayed, and also, if the message parameter is empty, would the error message be displayed, and how?

2024-02-14 11:16 UTC, skejeton commented
Ah I see the error is printed only if the code isn't 0, still unsure on what to do in case of the message being empty.

2024-02-14 11:25 UTC, vtereshkov requested changes

2024-02-14 11:25 UTC, vtereshkov commented on src/umka_vm.c
> +                pages->error->runtimeHandler(pages->error->context, 1, "Dangling pointer at %p", ptr);
@skejeton Let's define something like a `VM_RUNTIME_ERROR = 1` in `umka_vm.h` and use it here.

2024-02-14 11:25 UTC, vtereshkov commented on src/umka_expr.c
> +        genPushGlobalPtr(&comp->gen, "");
@skejeton An Umka string is not a C string. Please use `storageAddStr(&comp->storage, 0)`.

2024-02-14 11:30 UTC, vtereshkov requested changes

2024-02-14 11:30 UTC, vtereshkov commented on doc/lang.md
> +fn error(code: int, msg: str = "")
@skejeton If the error code is not optional, you'll have to fix all the occurences of `error()` (including Umka examples and tophat).

2024-02-14 11:32 UTC, vtereshkov commented
@skejeton Now I don't see any difference between `exit()` and `error(0)`. Do we need both?

2024-02-14 11:36 UTC, skejeton commented
I thin `exit` can be removed, though `error(0)` is a bit confusing even if practically equivalent, the only difference is that `exit`, currently exits out of a fiber while `error(0)` exits to the closest setjmp.

2024-02-14 11:44 UTC, skejeton commented
I think merging into `exit` works. Asking again, but if the `msg` is empty, should we output the stack trace, line info and other info or not? I think if someone writes a utility program that's very unnecessary clogging of stderr/out.

2024-02-14 11:47 UTC, marekmaskarinec commented
> @marekmaskarinec What do you think an `exit(code)` should do in a function called from `umkaCall()`?

What about switching to an integer return value and returning values in the libc fashion? A negative value would mean a runtime error. A positive value (or zero) would be the return code.

2024-02-14 11:51 UTC, marekmaskarinec commented on doc/lang.md
> +fn error(code: int, msg: str = "")
I don't think error should allow you to specify the return code. It should act just like any other runtime error.

2024-02-14 11:53 UTC, vtereshkov commented
> Asking again, but if the msg is empty, should we output the stack trace, line info and other info or not? I think if someone writes a utility program that's very unnecessary clogging of stderr/out.

@skejeton I think the end user can decide what to do. He/she will get an error code from `umkaRun`/`umkaCall`, request the `UmkaError` structure and analyze them (maybe in a fashion proposed by @marekmaskarinec).

2024-02-14 12:14 UTC, skejeton commented
I think it's implemented now.

2024-02-14 12:27 UTC, vtereshkov requested changes
I begin to like it.

2024-02-14 12:27 UTC, vtereshkov commented on examples/3dcam/3dcam.c
> +                bool umkaOk = umkaCall(umka, umkaDrawBodies, 0, NULL, NULL, NULL);
Remove the extra `NULL` and add ` == 0`

2024-02-14 12:27 UTC, vtereshkov commented on runtime/std.um
> +const runtimeError* = 1
Should it be documented?

2024-02-14 12:27 UTC, vtereshkov commented on src/umka_api.c
> +    comp->error.code = code;
Maybe also add `comp->error.code = 1` to the compile-time error handler?

2024-02-14 12:27 UTC, vtereshkov commented on src/umka_vm.h
> -    BUILTIN_ERROR
Please also remove the `"error"` item from the function name spellings in `umka_vm.c`.

2024-02-14 12:32 UTC, skejeton commented on src/umka_vm.h
> -    BUILTIN_ERROR
Fixed.

2024-02-14 12:32 UTC, skejeton commented on src/umka_api.c
> +    comp->error.code = code;
Fixed.

2024-02-14 12:32 UTC, skejeton commented on runtime/std.um
> +const runtimeError* = 1
Yes. Fixed.

2024-02-14 12:33 UTC, skejeton commented on examples/3dcam/3dcam.c
> +                bool umkaOk = umkaCall(umka, umkaDrawBodies, 0, NULL, NULL, NULL);
Fixed.

2024-02-14 12:57 UTC, vtereshkov commented
@skejeton If Marek approves this, we'll also need to rebuild the playground. If you cannot do it, I'll do it myself after this pull request is merged.

2024-02-14 13:05 UTC, skejeton commented
I rebuilt the playground, I also noticed that there's an error in `umka.c` that we didn't catch, I fixed it.

2024-02-14 13:05 UTC, marekmaskarinec commented
> @marekmaskarinec Do you agree with the proposed changes?
> 
>     * `exit()` accepts an error code and an optional error message
> 
>     * `error()` removed
> 
>     * `umkaRun()` and `umkaCall()` return `int`, i.e., the error code (0 is no error)

How does one distinguish between a runtime error and a code passed to `exit`?

BTW @skejeton we will need to figure out how to implement this in tophat. Currently `exit` isn't used because it would just quit the current `umkaCall`, so we have `window.quit` instead.

2024-02-14 13:08 UTC, vtereshkov commented
> How does one distinguish between a runtime error and a code passed to exit?

@marekmaskarinec @skejeton We can redefine `VM_RUNTIME_ERROR` (and `std.runtimeError`?) to -1.

2024-02-14 13:11 UTC, skejeton commented
> How does one distinguish between a runtime error and a code passed to `exit`?

If no message is provided it's not printed in the default runtime (umka.c).

2024-02-14 13:14 UTC, skejeton commented
> BTW @skejeton we will need to figure out how to implement this in tophat. Currently exit isn't used because it would just quit the current umkaCall, so we have window.quit instead.

We just use the returned value from `umkaCall` in `frame`

2024-02-14 13:32 UTC, marekmaskarinec commented
> > How does one distinguish between a runtime error and a code passed to `exit`?
> 
> If no message is provided it's not printed in the default runtime (umka.c). So `exit(code)` is equivalent to C's `exit`.

But there are also runtime errors generated by umka itself.

2024-02-14 13:32 UTC, skejeton commented
> > > How does one distinguish between a runtime error and a code passed to `exit`?
> > 
> > 
> > If no message is provided it's not printed in the default runtime (umka.c). So `exit(code)` is equivalent to C's `exit`.
> 
> But there are also runtime errors generated by umka itself.

Gotcha, I made runtime errors negative.

2024-02-14 14:41 UTC, vtereshkov commented
>  But there are also runtime errors generated by umka itself.

@marekmaskarinec All runtime errors produced by the Umka VM and standard library will return error code -1. Your custom codes in `exit` can be any integers. Is it what you're expecting?

2024-02-15 17:10 UTC, merged