Add -vet option to umka cli thing
vtereshkov/umka-lang pull request #56
Opened 2021-03-29 18:20 UTC by marekmaskarinec

You can now only check, if program has no errors without running it.

2021-03-29 20:20 UTC, vtereshkov requested changes
A good idea! But the new parameter has to be allowed at any place, not necessarily at `argv[2]`. Please also change `compileOnly` to `bool` and follow the curly bracket style used in  my C files.

2021-03-29 20:33 UTC, Mazdaywik commented
Commit b5b92b3 removes Vim syntax file.

2021-03-29 20:45 UTC, marekmaskarinec commented
Oh, sorry. Forgot about the brackets. I will fix it tomorrow.

2021-03-29 21:49 UTC, marekmaskarinec commented
@Mazdaywik yes, that is wanted. The syntax file was never merged in the first place and I made a separate [repository](https://github.com/marekmaskarinec/vim-umka) for it.

2021-03-30 07:45 UTC, marekmaskarinec commented
@vtereshkov it should all be fixed now

2021-03-31 04:54 UTC, Mazdaywik requested changes
Please change tabulations to spaces.

2021-03-31 07:27 UTC, Mazdaywik approved these changes
@vtereshkov should approve it.

2021-03-31 07:27 UTC, Mazdaywik commented on src/umka.c
> +        {
Ok.

2021-03-31 21:40 UTC, vtereshkov approved these changes
@marekmaskarinec I approve your pull request, though I still have doubts about reading the command-line arguments correctly. So I'll merge and test it. I also think of renaming `vet` into `check`, as this command just runs the compiler and does not use extra heuristics involved by Go's `vet`.

2021-03-31 21:40 UTC, merged

2021-03-31 21:51 UTC, marekmaskarinec commented
Oh. I'm sorry about the libumka.wasm file. I've been experimenting a bit and staged it when fixing the tabs.

2021-03-31 23:11 UTC, vtereshkov commented
@marekmaskarinec I have fixed two problems:
* My former logic had a fixed step of 2 when parsing the command-line arguments, so you couldn't parse `-vet` without specifying some additional data, like in `-stack` or `-storage`. Now the step is variable. This also allows me to construct the assembly listing name automatically.
* In the compile-only mode, you terminated the program skipping `umkaFree()`. This is a possible memory leak, though an OS would probably deallocate the memory for you.

Please check the `master` branch and report any remaining inconsistencies.